version: "3.9"

services:
  backend:
    image: python:3.12-slim
    working_dir: /app
    command: sh -c "pip install --no-cache-dir fastapi uvicorn[standard] && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app
    expose:
      - "8000"

  frontend:
    image: node:20
    working_dir: /app
    command: sh -c "npm i && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app
    expose:
      - "5173"

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
